project_id = "gapzhhgkbojwamfrgnxk"

[functions.process-tick]
verify_jwt = false

[functions.colonize-cell]
verify_jwt = false

[functions.found-city]
verify_jwt = false

[functions.create-market-order]
verify_jwt = false

[functions.cancel-market-order]
verify_jwt = false
