project_id = "gapzhhgkbojwamfrgnxk"

[functions.process-tick]
verify_jwt = false

[functions.colonize-cell]
verify_jwt = false

[functions.found-city]
verify_jwt = false

[functions.create-market-order]
verify_jwt = false

[functions.cancel-market-order]
verify_jwt = false

[functions.sell-cell]
verify_jwt = false

[functions.execute-trade-deal]
verify_jwt = false

[functions.declare-war]
verify_jwt = false

[functions.create-law]
verify_jwt = false

[functions.cast-vote]
verify_jwt = false

[functions.create-territory]
verify_jwt = false
